# The api key, secret key, and canvas page name are required to get started
# Tunnel configuration is only needed if you are going to use the facebooker:tunnel Rake tasks
# Your callback url in Facebook should be set to http://public_host:public_port
# If you're building a Facebook connect site, 
#    change the value of set_asset_host_to_callback_url to false
# To develop for the new profile design, add the following key..
# api: new
# remove the key or set it to anything else to use the old facebook design.
# This should only be necessary until the final version of the new profile is released.

<% h = YAML.load_file("#{RAILS_ROOT}/config/fb_passwd.yml") %>

development:
  api_key: <%= h['api_key'] %>
  secret_key: <%= h['secret_key'] %>
  canvas_page_name: setsolver
  callback_url: http://173.66.113.86:15000/
  pretty_errors: true
  set_asset_host_to_callback_url: true

test:
  api_key: <%= h['api_key'] %>
  secret_key: <%= h['secret_key'] %>
  canvas_page_name: setsolver
  callback_url: http://173.66.113.86:15000/
  pretty_errors: true
  set_asset_host_to_callback_url: true

production:
  api_key: <%= h['api_key'] %>
  secret_key: <%= h['secret_key'] %>
  canvas_page_name: setsolver
  callback_url: http://173.66.113.86:15000/
  pretty_errors: true
  set_asset_host_to_callback_url: true

